@GamePacks_Service_HostAddress = http://localhost:3000

POST {{GamePacks_Service_HostAddress}}/api/v1/packs
Content-Type: application/json

{
  "packName": "The School Pack",
  "active": true,
  "price": 10,
  "content": ["furniture.whiteboard"],
  "childPackIds": []
}
