x-database-details: &DATABASE_DETAILS
  Database__ConnectionString: "Server=gamepacks-dbserver;Port=5432;Database=gamespacks-db;User Id=postgress;Password=mypassword123!;"

services:
  gamepacks-service:
    build:
      context: .
      dockerfile: ./GamePacks.Service/Dockerfile
      args: 
        BUILD_CONFIGURATION: Release
    environment:
      <<: *DATABASE_DETAILS
    networks:
      - gamepacks-service-network
    ports:
      - "3000:5049"
    depends_on:
      - gamepacks-migrations

  gamepacks-migrations:
    build:
      context: .
      dockerfile: ./GamePacks.Migrations/Dockerfile
      args: 
        BUILD_CONFIGURATION: Release
    environment:
      <<: *DATABASE_DETAILS
    networks:
      - gamepacks-service-network
    depends_on:
      - gamepacks-dbserver
    restart: on-failure

  gamepacks-dbserver:
    image: postgres:16  
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: mypassword123!
    ports:
      - "5432:5432"
    networks:
      - gamepacks-service-network
    restart: always

networks:
  gamepacks-service-network:
    driver: bridge